/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as ProdutoSlugRouteImport } from './routes/produto.$slug'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminConfigRouteImport } from './routes/_authenticated/admin.config'
import { Route as AuthenticatedAdminProdutoIdRouteImport } from './routes/_authenticated/admin.produto.$id'
import { Route as ApiPublicFotoSplatRouteImport } from './routes/api/public/foto.$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutoSlugRoute = ProdutoSlugRouteImport.update({
  id: '/produto/$slug',
  path: '/produto/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminConfigRoute =
  AuthenticatedAdminConfigRouteImport.update({
    id: '/admin/config',
    path: '/admin/config',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminProdutoIdRoute =
  AuthenticatedAdminProdutoIdRouteImport.update({
    id: '/admin/produto/$id',
    path: '/admin/produto/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicFotoSplatRoute = ApiPublicFotoSplatRouteImport.update({
  id: '/api/public/foto/$',
  path: '/api/public/foto/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/privacidade': typeof PrivacidadeRoute
  '/admin/login': typeof AdminLoginRoute
  '/produto/$slug': typeof ProdutoSlugRoute
  '/admin/config': typeof AuthenticatedAdminConfigRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/produto/$id': typeof AuthenticatedAdminProdutoIdRoute
  '/api/public/foto/$': typeof ApiPublicFotoSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/privacidade': typeof PrivacidadeRoute
  '/admin/login': typeof AdminLoginRoute
  '/produto/$slug': typeof ProdutoSlugRoute
  '/admin/config': typeof AuthenticatedAdminConfigRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/produto/$id': typeof AuthenticatedAdminProdutoIdRoute
  '/api/public/foto/$': typeof ApiPublicFotoSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/privacidade': typeof PrivacidadeRoute
  '/admin/login': typeof AdminLoginRoute
  '/produto/$slug': typeof ProdutoSlugRoute
  '/_authenticated/admin/config': typeof AuthenticatedAdminConfigRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/produto/$id': typeof AuthenticatedAdminProdutoIdRoute
  '/api/public/foto/$': typeof ApiPublicFotoSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/privacidade'
    | '/admin/login'
    | '/produto/$slug'
    | '/admin/config'
    | '/admin/'
    | '/admin/produto/$id'
    | '/api/public/foto/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/privacidade'
    | '/admin/login'
    | '/produto/$slug'
    | '/admin/config'
    | '/admin'
    | '/admin/produto/$id'
    | '/api/public/foto/$'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/privacidade'
    | '/admin/login'
    | '/produto/$slug'
    | '/_authenticated/admin/config'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/produto/$id'
    | '/api/public/foto/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  PrivacidadeRoute: typeof PrivacidadeRoute
  AdminLoginRoute: typeof AdminLoginRoute
  ProdutoSlugRoute: typeof ProdutoSlugRoute
  ApiPublicFotoSplatRoute: typeof ApiPublicFotoSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produto/$slug': {
      id: '/produto/$slug'
      path: '/produto/$slug'
      fullPath: '/produto/$slug'
      preLoaderRoute: typeof ProdutoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/config': {
      id: '/_authenticated/admin/config'
      path: '/admin/config'
      fullPath: '/admin/config'
      preLoaderRoute: typeof AuthenticatedAdminConfigRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/produto/$id': {
      id: '/_authenticated/admin/produto/$id'
      path: '/admin/produto/$id'
      fullPath: '/admin/produto/$id'
      preLoaderRoute: typeof AuthenticatedAdminProdutoIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/foto/$': {
      id: '/api/public/foto/$'
      path: '/api/public/foto/$'
      fullPath: '/api/public/foto/$'
      preLoaderRoute: typeof ApiPublicFotoSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminConfigRoute: typeof AuthenticatedAdminConfigRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminProdutoIdRoute: typeof AuthenticatedAdminProdutoIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminConfigRoute: AuthenticatedAdminConfigRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminProdutoIdRoute: AuthenticatedAdminProdutoIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  PrivacidadeRoute: PrivacidadeRoute,
  AdminLoginRoute: AdminLoginRoute,
  ProdutoSlugRoute: ProdutoSlugRoute,
  ApiPublicFotoSplatRoute: ApiPublicFotoSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
